The static method java.lang.ThreadLocal.withInitial is added  On line 99
javapathfinder/jpf-core pull request #301
Opened 2021-11-09 06:44 UTC by gaurangkudale

Added method 

 public static <S> ThreadLocal<S> withInitial(Supplier<? extends S> supplier) {
    return new SuppliedThreadLocal<>(supplier);
  }

2021-11-09 08:07 UTC, cyrille-artho commented
Thank you for your contribution. Is there a unit test available that fails without the new method, so we can confirm that it works as intended? If there is no existing test, could you please try to create one?

2021-11-09 09:35 UTC, gaurangkudale commented
> Thank you for your contribution. Is there a unit test available that fails without the new method, so we can confirm that it works as intended? If there is no existing test, could you please try to create one?

@cyrille-artho Can you please help me with the unit test because I'm not familiar with it

2021-11-09 10:29 UTC, cyrille-artho commented
The key challenge is to find a small program that fails without your patch but which works with it. (Possibly this could mean that under a certain version of the JDK, the code may not compile without the patch.)
After that, the program can be adapted as a unit test.
See https://github.com/javapathfinder/jpf-core/wiki/Writing-JPF-tests in the wiki for guidance on how to write unit tests.
I can help you with the final step, but as I said, finding an example is the most important part.

2021-11-09 15:24 UTC, gaurangkudale commented
Hi @cyrille-artho Can you please tell me how to find an example?

2021-11-09 18:17 UTC, cyrille-artho commented
Hi Guarang,
Coming up with a good example/test can indeed be difficult. The best way to find code snippets/examples is by using a web search.
For example, I found these fragments that may make a working example (adding the assertion at the end):
```
ThreadLocal<Integer> threadLocal = ThreadLocal.withInitial(() -> 1);
Integer result = threadLocalValue.get();
assertEquals(result, 1);
```
I assume that this either won't compile without your patch (as constructor with the "supplier" lambda expression argument is not available without it) or will not return the correct value.
Try running a small program like this with the old JPF (without your patch) and the new JPF (with your patch) first, and then convert the program into a unit test using the instructions on the wiki (link in the above post).

2021-11-10 10:24 UTC, gaurangkudale commented
Hi @cyrille-artho,
I have written some code to test please look at it
` import javax.sound.sampled.SourceDataLine;

public class ThreadLocalInitialValueExample {
    public static <MyObject> void main(String[] args) {
        ThreadLocal<MyObject> threadLocal1 = new ThreadLocal<>(){
            @Override
            protected MyObject initialValue() {
                return new MyObject();
            }
        };
        ThreadLocal<MyObject> threadLocal2 = 
            ThreadLocal.withInitial(() -> {
                return new MyObject();
            });

        Thread thread1 = new Thread(() -> {
            System.out.println("ThreadLocal1: "+ threadLocal1.get());
            System.out.println("ThreadLocal2: "+ threadLocal2.get());
        });

        Thread thread2 = new Thread(() -> {
            System.out.println("threadLocal1: " + threadLocal1.get());
            System.out.println("ThreadLocal2: "+ threadLocal2.get());
        });

    }
}`

2021-11-11 11:53 UTC, cyrille-artho commented
Hi,
Something seems to have gone slightly wrong when copying the code. Please copy complete code or link to an example. (Unfortunately, the simple issue tracker on GitHub does not support file attachments.)

2021-11-11 19:58 UTC, gaurangkudale commented
Hi @cyrille-artho ,
I've attached the link of file please g through it

https://kjeieduin-my.sharepoint.com/:t:/g/personal/14seit_tcoer_kjei_edu_in/EWkMXzPF1JFMkREt2iyXFWEBv68DWicZMbP0I1LnNRqyPw?e=PqsSmH

2021-11-11 20:02 UTC, gaurangkudale commented
@cyrille-artho 
I've also created one more example for unit test and linked is attached below

https://kjeieduin-my.sharepoint.com/:t:/g/personal/14seit_tcoer_kjei_edu_in/EWSO7PLBETRKvm900jwuIHoB4bL0mHgCKyRrSPQ8pCKlew?e=3TkVKc

2021-11-12 13:41 UTC, gaurangkudale commented
Hi @cyrille-artho 
Did you check the unit test?

2021-11-12 19:20 UTC, cyrille-artho commented
Could you please complete the unit test so it has an assertion that checks the behavior? The output is not easy to inspect when run on Gradle's test runner. The test code was also not 100 % complete so it does not compile without the additional imports for JUnit.

2021-11-14 09:39 UTC, gaurangkudale commented
Hi @cyrille-artho,
I have gone through the unit test but I'm not familiar with it can somebody help me to create a unit test?

2021-11-15 08:37 UTC, cyrille-artho commented
As a first step, simply add one of your examples to the pull request (as a program that runs from `main`). I can then modify it to work as a unit test.

2021-11-17 15:16 UTC, gaurangkudale commented
> As a first step, simply add one of your examples to the pull request (as a program that runs from `main`). I can then modify it to work as a unit test.

Hi @cyrille-artho, 
as you said I've added the example with the main method

2021-11-18 11:34 UTC, gaurangkudale commented
Hi @cyrille-artho 
did you checked the example?

2021-11-18 15:52 UTC, cyrille-artho commented
Looks good, and I have triggered the CI build. I will run the tests on my local machine later this week or next week, as soon as I have time.

2021-11-18 16:09 UTC, gaurangkudale commented
@cyrille-artho 
Sure

2021-11-18 16:50 UTC, gaurangkudale commented
Hi @cyrille-artho,
Added the new test file under  "src/tests"

2021-11-19 08:10 UTC, gaurangkudale commented
Hi @cyrille-artho 
Did you check the example is it good?

2021-11-19 15:05 UTC, cyrille-artho requested changes
Hi Guarang,
Great job! This version works perfectly. I'd just like you to make two small cosmetic changes before merging.

2021-11-19 15:05 UTC, cyrille-artho commented on src/classes/java/lang/ThreadLocal.java
> +import java.sql.Date;
Remove these two unused imports.

2021-11-19 15:05 UTC, cyrille-artho commented on src/tests/ThreadLocalTest/App.java
> +}
Add a newline character (line break) at the end of the last line.

2021-11-19 16:30 UTC, gaurangkudale commented
Hi @cyrille-artho Changes are done

2021-11-19 16:45 UTC, cyrille-artho commented
Hi,
There was a misunderstanding: What I meant was to remove the unused import statements in the implementation, and add a newline character at the end of the last source code line. You have added a print statement that does not compile. The previous revision was good except for these two minor issues (and for some reason, the PR did not show the completely refreshed version on GitHub, but I will look at this again later once you have a revised version that compiles and passes the tests).

2021-11-19 16:50 UTC, gaurangkudale commented
> Hi, There was a misunderstanding: What I meant was to remove the unused import statements in the implementation, and add a newline character at the end of the last source code line. You have added a print statement that does not compile. The previous revision was good except for these two minor issues (and for some reason, the PR did not show the completely refreshed version on GitHub, but I will look at this again later once you have a revised version that compiles and passes the tests).

okay so now I only need to add a new line character like `\n` is that right

2021-11-19 17:38 UTC, gaurangkudale commented
waiting for reply

2021-11-20 04:45 UTC, gaurangkudale commented
Hi @cyrille-artho 
Looking for your guidance regarding the Tests

2021-11-20 06:59 UTC, gaurangkudale commented
In my local machine if I remove these two imports then it is showing me errors because I've used those packages in the unit test
I've attached the screenshot in the link 
maybe that's why it is not passing the test cases please look into it

[https://kjeieduin-my.sharepoint.com/:i:/g/personal/14seit_tcoer_kjei_edu_in/EemLvc6Z8oJChLmN0Csq6pkB-3Uqv2tkNfQpDquWWLerjg?e=MPvrXt](url)

2021-11-20 09:32 UTC, gaurangkudale commented on src/classes/java/lang/ThreadLocal.java
> +import java.sql.Date;
Changes are done

2021-11-20 09:45 UTC, gaurangkudale commented
Hi @cyrille-artho, 

- As you suggested the changes I've done the first change which is to remove unused imports from 'src/classes/java/lang/ThreadLocal.java'
- Can you please explain to me the second change so that I'll work on it

2021-11-20 13:34 UTC, cyrille-artho approved these changes

2021-11-20 13:35 UTC, merged

2021-11-20 13:35 UTC, cyrille-artho commented
Looks good. Thank you very much for your effort and patience.

2021-11-20 13:54 UTC, gaurangkudale commented
@cyrille-artho Thank you for guiding me for my First contribution really excited to do more

2021-11-22 07:28 UTC, cyrille-artho commented
You're welcome. There are many open issues on the issue tracker left, and other features that are not yet tested (or documented as issues), for example, the `java.util.stream` API.

2021-11-22 07:56 UTC, gaurangkudale commented
> You're welcome. There are many open issues on the issue tracker left, and other features that are not yet tested (or documented as issues), for example, the `java.util.stream` API.

Hi @cyrille-artho, 
Can you please share the more details about this issue so that I will work on it

2021-11-22 08:44 UTC, cyrille-artho commented
I have not documented anything yet (and doing so on the issue tracker would be a good start).
The problem is the following:
We don't have any unit tests for the new Java streams collections (`java.util.stream`):

https://docs.oracle.com/javase/8/docs/api/java/util/stream/package-summary.html

Simply including a few examples would be helpful to see if JPF can handle these cases at all (there may be missing native peer classes/methods), and what problems there might be.

I have created a new issue for this: https://github.com/javapathfinder/jpf-core/issues/302
So let's continue discussions there.