Update VarTracker.java
javapathfinder/jpf-core pull request #428
Opened 2023-12-20 12:18 UTC by Ayush-Thakur-geek

FOR issue #380

2023-12-23 15:00 UTC, cyrille-artho commented
Thanks, your patch looks good. Could you please try to add a unit test as well so that we have a failing test (from your example) that shows that the patch is needed?

2023-12-26 12:26 UTC, cyrille-artho requested changes
The new change is unrelated and not needed; please revert it.
Instead, please try to add a unit test that fails if your fix to `VarTracker` is not applied yet.

2023-12-26 12:26 UTC, cyrille-artho commented on src/classes/modules/java.logging/java/util/logging/FileHandler.java
This change is not necessary; the module name is not part of the package name (but it is reflected in the file name).

2024-03-29 14:15 UTC, closed without merging

2024-05-20 23:05 UTC, abimael-turing commented
@cyrille-artho If you would like, you can assign this issue to me!