fixing issue Orphan NativePeer method with Java 11.0.20.1 #421
javapathfinder/jpf-core pull request #431
Opened 2024-01-08 18:28 UTC by adysinghh

fix #421

2024-01-09 09:29 UTC, cyrille-artho requested changes
Thank you for the update. Please try to minimize the changes; if it is not possible to add a unit test to check against warnings of JPF, then there is no need to add imports for the `junit` test packages.

2024-01-09 09:29 UTC, cyrille-artho commented on src/peers/gov/nasa/jpf/vm/JPF_jdk_internal_misc_Unsafe.java
> +  }
Please try to avoid introducing extra formatting changes, as this may make it more difficult to merge your patch in other branches later.

2024-01-09 09:29 UTC, cyrille-artho commented on src/peers/gov/nasa/jpf/vm/JPF_jdk_internal_misc_Unsafe.java
> +
Try to remove this change as well.

2024-01-09 09:29 UTC, cyrille-artho commented on src/peers/gov/nasa/jpf/vm/JPF_jdk_internal_misc_Unsafe.java
> +import junit.Test;
Are these two imports needed? You do not (yet) add a new test in this patch.

2024-01-12 15:17 UTC, adysinghh commented
@cyrille-artho Hi, I had incorporated all the suggested changes

2024-01-13 19:05 UTC, cyrille-artho requested changes
Thank you for the update. This version is a step forward but still has some changes that do not seem to relate directly to the incorrectly named native peer.
Can you please try to make a minimal patch that does not change any other lines? There are several changes (I've highlighted some of them) that add or remove spaces or empty lines. There is also one change that removes an @MJI method. While the tests still all pass, there may be functionality that the unit tests do not cover but rely on that @MJI method.

2024-01-13 19:05 UTC, cyrille-artho commented on src/peers/gov/nasa/jpf/vm/JPF_jdk_internal_misc_Unsafe.java
> -  public int addressSize0____I (MJIEnv env, int objRef) {
This function does not seem to be tested by the current unit tests, but are you sure it is not needed at all?

2024-01-13 19:05 UTC, cyrille-artho commented on src/peers/gov/nasa/jpf/vm/JPF_jdk_internal_misc_Unsafe.java
> +  public long objectFieldOffset__Ljava_lang_reflect_Field_2__J(MJIEnv env, int unsafeRef, int fieldRef) {
Please add the space before the "(" back so we do not have extra changes in the patch; this is important to make future merges to other branches easier.

2024-01-14 18:32 UTC, adysinghh commented
@cyrille-artho Thanks for the valuable feedback! I've incorporated the suggested changes, keeping modifications minimal. Retained necessary methods, removed extra spaces, and ensured consistent spacing.

- Removed unnecessary spaces and empty lines.
- Retained @MJI methods as per feedback.
- Ensured consistent spacing in method signatures.

Please review the changes.

2024-01-15 07:37 UTC, cyrille-artho commented
Thanks for adding the code back. Please try to add it back in the same way it was before, as there are still two changes that merely reformat code, which is best avoided (an empty line at the beginning and reordered/reformatted methods at the end).

2024-03-02 18:18 UTC, adysinghh commented
@cyrille-artho I had made the changes please review.

2024-03-03 07:21 UTC, cyrille-artho requested changes
Hi,
Please try to isolate the first change. If you are not familiar with "diff" and "patch", you can try to apply the first change again manually on a new branch and make a new PR.
Thank you for your perseverance!

2024-03-03 07:21 UTC, cyrille-artho commented on src/peers/gov/nasa/jpf/vm/JPF_jdk_internal_misc_Unsafe.java
> +
Can you please revert the second change that swaps the two methods, so we have a patch that only has the first (functional) change?

2024-08-14 14:29 UTC, shreyasCs012 commented
the native peers method present in the `\src\peers\gov\nasa\jpf\vm` had a  "mangled" which was old so it has been corrected to the new location which is `\jdk\internal\misc`

2024-08-14 16:38 UTC, closed without merging

2024-08-14 16:38 UTC, cyrille-artho commented
Subsumed by PR #492