BufferTest Codes and Changes
javapathfinder/jpf-core pull request #479
Opened 2024-07-21 17:01 UTC by eklaDFF

2024-07-21 18:29 UTC, cyrille-artho requested changes
Looks good! Furthermore, the unit tests all pass now, which is great!
All I can see are two minor things: We want to use git to handle changes, so we want to avoid commenting out old code and instead remove it. This makes it easier to maintain the code in the long term.
Please update the PR accordingly, and I will merge it.

2024-07-21 18:29 UTC, cyrille-artho commented on src/classes/modules/java.base/java/lang/String.java
> +//	native public void getChars(int srcBegin, int srcEnd, char dst[], int dstBegin);
remove instead of commenting out

2024-07-21 18:29 UTC, cyrille-artho commented on src/classes/modules/java.base/java/lang/String.java
> -		getBytes(srcPos,(srcPos+length),dst,dstBegin);
remove instead of commenting out

2024-07-21 19:12 UTC, eklaDFF commented
@cyrille-artho 
Made those changes

2024-07-21 19:17 UTC, eklaDFF commented on src/classes/modules/java.base/java/lang/String.java
> +//	native public void getChars(int srcBegin, int srcEnd, char dst[], int dstBegin);
Made those changes

2024-07-22 07:08 UTC, cyrille-artho approved these changes

2024-07-22 07:08 UTC, merged